import type { DefaultAlgSheet } from "../types";

export const OCLS: DefaultAlgSheet = {
  name: "OCLS",
  algSets: [
    {
      name: "",
      algs: [
        { name: "", alg: "r U R' U' r' F R F'" },
        { name: "", alg: "R2 D R' U2 R D' R' U2 R'" },
        { name: "", alg: "F' r U R' U' r' F R" },
        { name: "", alg: "R U R' U R U' R' U R U2 R'" },
        { name: "", alg: "R' U2 R2 U R2 U R2 U2 R'" },
        { name: "", alg: "R U R' U R U2 R'" },
        { name: "", alg: "R U2 R' U' R U' R'" },
      ],
    },
    {
      name: "",
      algs: [
        { name: "", alg: "R2 D R' U' R D' R2 U' R U2 R'" },
        { name: "", alg: "R2 U2' R' U' R U' R' U2 R'" },
        { name: "", alg: "R U2' R' U2 R U2' R' U' R U R'" },
        { name: "", alg: "R2 U2' R' U' R U' R2' U' R U' R'" },
        { name: "", alg: "R U R' U' R U2' R' U' R U R'" },
        { name: "", alg: "R U' R' U' R U R' U' R U2' R'" },
        { name: "", alg: "R U R D R' U2 R D' R2' U2' R U' R'" },
        { name: "", alg: "R U2 R' U2 R U R' U' R U2 R' U2 R U R'" },
      ],
    },
    {
      name: "",
      algs: [
        { name: "", alg: "R U2' R' U R2 D R' U R D' R2'" },
        { name: "", alg: "R U2 R U R' U R U2' R2'" },
        { name: "", alg: "R U' R' U R U2' R' U2 R U2' R'" },
        { name: "", alg: "R U2' R' U R U' R' U R U R'" },
        { name: "", alg: "R U' R' U R U2 R' U R U' R'" },
        { name: "", alg: "R U R' U R2 U R' U R U2' R2'" },
        { name: "", alg: "R U R' U2 R2 D R' U2 R D' R' U' R'" },
        { name: "", alg: "R U' R' U2 R U2 R' U R U' R' U2 R U2 R'" },
      ],
    },
    {
      name: "",
      algs: [
        { name: "", alg: "(U) D' R' D R U R' D' R D" },
        { name: "", alg: "(U2) R U R' U' R U' R' U R U' R'" },
        { name: "", alg: "R U R D R' U2 R D' R' U R'" },
        { name: "", alg: "(U) R' F R U R U' R' F' R U R'" },
        { name: "", alg: "(U2) R U R' U' R U' R' U2 R U2 R'" },
        { name: "", alg: "R U2 R' U2 R' F' R U R U' R' F" },
        { name: "", alg: "(U) R U' R' U' R U2' R'" },
        { name: "", alg: "(U) R U' R' U2 R U' R'" },
        { name: "", alg: "(U2) R U' R U2 R' U' R U' R2'" },
        { name: "", alg: "(U) R U' R2 D' R U2 R' D R2 U' R'" },
        { name: "", alg: "F' R U2 R' U' R U' R' F" },
        { name: "", alg: "(U') R' D' R U2 R' D R2 U' R' U2 R U' R'" },
        { name: "", alg: "R U R2 D' R U2 R' D R2 U R'" },
        { name: "", alg: "(U') R' U2 R U R U' R2 U2 R2 U' R'" },
        { name: "", alg: "(U2) R U' R2' U2' R U R' U R2 U R'" },
        { name: "", alg: "D R' U' R U2 R' U' R D'" },
        { name: "", alg: "R' F' R U R U' R' F U' R U2 R'" },
        { name: "", alg: "(U') R2 U R' U R U2' R' U R'" },
        { name: "", alg: "(U) R U' R' U' F' R U2' R' U2 R' F R" },
        { name: "", alg: "(U') R U2 R' U' R U R' U R U R'" },
        { name: "", alg: "R U' R' U2 R U2 R' U2 R U' R'" },
        { name: "", alg: "(U2) R U' R' U2 R U2 R' U R U' R' U' R U R'" },
        { name: "", alg: "(U') L U' R U R' L' U R U2 R'" },
        { name: "", alg: "(U) R U' R' U' R' U' R2 U' R2 U2 R" },
        { name: "", alg: "(U) R U' R' U' R U' R' U R U2 R'" },
        { name: "", alg: "(U') R U R' U R U R' U' R U2 R'" },
        { name: "", alg: "(U) R U' R' U2 R2 D R' U' R D' R2'" },
      ],
    },
    {
      name: "",
      algs: [
        { name: "", alg: "(U) R' D' R U R' D R" },
        { name: "", alg: "(U') R U R2' D' r U2 r' D R" },
        { name: "", alg: "(U) R U2' R' U R U2' R' U R U2' R'" },
        { name: "", alg: "(U) R U2' R' U R U R'" },
        { name: "", alg: "(U2) R U R' U' R' F' R U R U' R' F" },
        { name: "", alg: "F R U R' U' R' F' R U' R U R'" },
        { name: "", alg: "R U2' R' U2 R U R' U' R U R'" },
        { name: "", alg: "(U') R' D' R U R' U' R U' R' U2 D R" },
        { name: "", alg: "(U') R U' R' U R U R' U' R U R'" },
        { name: "", alg: "(U') R' D' R U2 R' D R2 U2' R' U R U R'" },
        { name: "", alg: "R U2' R' U R U2' R' U2 R U R'" },
        { name: "", alg: "R U' R' U2 R U R' U R U R'" },
        { name: "", alg: "(U2) F' R' U2' R U R' U R U F" },
        { name: "", alg: "(U') R' D' R U R' D R U R U2 R' U R U R'" },
        { name: "", alg: "(U2) F' U' R U R' U R U2' R' U2 F" },
        { name: "", alg: "R' U' D' R U' R' U2 D R" },
        { name: "", alg: "(U2) R U' R2' F' R U2 R U2' R' F R U R'" },
        { name: "", alg: "R U' R' U R U' R' U' R U R'" },
        { name: "", alg: "(U') R U R' U2 R U R'" },
        { name: "", alg: "R U' R' U2 R U' R2 D' R U R' D R" },
        { name: "", alg: "(U) R U2 R' U' L R U' R' U L'" },
        { name: "", alg: "(U') R2 D R' U R D' R2' U2' R U R'" },
        { name: "", alg: "(U') R U R' U2 R U2 R' U R U2 R'" },
        { name: "", alg: "R U2 R' U R U2 L U' R' U L'" },
        { name: "", alg: "(U) R' D' R U R' D R2 U R' U R U2 R'" },
        { name: "", alg: "(U2) R U2 R' U' R U R' U2 R U' R' U R U' R'" },
        { name: "", alg: "(U2) R U' R' U2 R U R' U2 R U' R' U R U' R'" },
      ],
    },
    {
      name: "",
      algs: [
        { name: "", alg: "R2' U2' R2 U' R2' U' R2" },
        { name: "", alg: "(U') R U2' R' U' R U2' R' U' R U2' R'" },
        { name: "", alg: "R U' R' U R U R' U2 R U2' R'" },
        { name: "", alg: "R U' R' U R U R' U R U' R'" },
        { name: "", alg: "R F' r U R' U' r' F" },
        { name: "", alg: "R U' R' U L U' R U R' L'" },
        { name: "", alg: "(U) R U R' U' L U' R U R' L'" },
        { name: "", alg: "F' R U R' U R U2 R' F" },
        { name: "", alg: "(U) R U2' R' U2 R U2' R' U R U' R'" },
        { name: "", alg: "R U R2' D' R U' R' D R U2 R U2' R'" },
        { name: "", alg: "(U2) R U2 R' U' R U' R' U R U' R' U2 R U' R'" },
        { name: "", alg: "(U') F' R U R' U' R' F R2 U2 R' U R U' R'" },
        { name: "", alg: "(U') R U R' U' R U2' R' U R U' R'" },
        { name: "", alg: "(U') R U' R' U R U' R' U R U' R'" },
        { name: "", alg: "R U' R' U' R U' R' U2 R U R'" },
        { name: "", alg: "(U) R U R' U R U' R' U2 R U R'" },
        { name: "", alg: "(U2) L' U2 R2' U2' R2 U' R2' U' R2 L" },
        { name: "", alg: "(U') R U R' U' R U2 R' U2 R U2 R'" },
        { name: "", alg: "(U) R F' U R' U R U2 F R'" },
        { name: "", alg: "R U2' R' U2 R U' R' U R U' R'" },
        { name: "", alg: "(U) R' U' R U R U R' U2 R' U2 R U R U2 R'" },
        { name: "", alg: "(U2) R U' R' U2 R2 D R' U2 R D' R' U R'" },
        { name: "", alg: "(U') R U' R' U R U' R' U R U R' U' R U' R'" },
        { name: "", alg: "(U') R U2' R' U' R U2' R' U2 R U' R'" },
        { name: "", alg: "(U) R U R' U' R U R' U2 R U2' R'" },
        { name: "", alg: "(U) R U R' U2 F R U R' U' R' F' R" },
        { name: "", alg: "(U2) R U R' U2 R U2' R' U2 R U R'" },
      ],
    },
    {
      name: "",
      algs: [
        { name: "", alg: "(U) R' D' R U R' D R2 U' R'" },
        { name: "", alg: "R2 D' R2 U R U' R' U R' D R2 U' R'" },
        { name: "", alg: "(U) R' F' R U2 R U' R' U R U2 R' F" },
        { name: "", alg: "(U) R' D' R U' R' D R U2 R U' R'" },
        { name: "", alg: "(U) R U' R' U2 R' U' R2 U' R2 U2 R" },
        { name: "", alg: "R U' R' U' R U2 R' U' R U2 R'" },
        { name: "", alg: "(U) R U' R' U2 R U2 R'" },
        { name: "", alg: "(U2) R U' R' U' R U' R' U2 R U' R'" },
        { name: "", alg: "R U R' U R2 U2 R2 U' R2 U' R2" },
        { name: "", alg: "(U') R U R' U' R U' R' U2 R U R'" },
        { name: "", alg: "(U) R U' R' U R U' R'" },
        { name: "", alg: "(U) R U' R' U R U R' U' R U' R'" },
        { name: "", alg: "R2 U R' U R U' R' U R U2 R2" },
        { name: "", alg: "(U) R' D' R U R' D R U R U2 R'" },
        { name: "", alg: "(U) R U2 R' U2 R U' R' U2 R U R'" },
        { name: "", alg: "R U' R2 D' R U2 R' D R U R U' R'" },
        { name: "", alg: "(U) R' D' R U2 R' D R2 U2 R'" },
        { name: "", alg: "(U) R U' R' U R' D' R U R' D R2 U2 R'" },
        { name: "", alg: "R U2 R' U' R U2 R' U2 R U2 R'" },
        { name: "", alg: "(U) L R U' R' U R U' R' U L'" },
        { name: "", alg: "(U) R U' R2 F R U R U' R' F'" },
        { name: "", alg: "(U) R U' R' U2 R U' R' U R U2 R'" },
        { name: "", alg: "(U) R U' R' L' U R U' R' L" },
        { name: "", alg: "(U') R2 D R' U' R D' R' U2 R' U' R U2 R'" },
        { name: "", alg: "(U') R' D' R U' R' D R2 U2 R' U2 R U' R'" },
        { name: "", alg: "(U2) R U2 R' U2 R U' R2 D' R U2 R' D R" },
        { name: "", alg: "(U') R U' R2 D' R U' R' D R U2 R U2 R'" },
      ],
    },
    {
      name: "",
      algs: [
        { name: "", alg: "F' R U2 R' U2 R' F R2 U R'" },
        { name: "", alg: "R U R2 D' R U' R' D R" },
        { name: "", alg: "D' R' D R U2 R' D' R U2 D R U R'" },
        { name: "", alg: "R' D' R U R' D R2 U' R'" },
        { name: "", alg: "(U') R U2 R' U R U2 R' U R U R'" },
        { name: "", alg: "R U2 R' U2 R U R'" },
        { name: "", alg: "(U') R U R' U2 R U R' U R U R'" },
        { name: "", alg: "(U) R U R' U' R U2 R' U R U2 R'" },
        { name: "", alg: "L' U R U' L U2 R' U' R U R'" },
        { name: "", alg: "R U2 L U' R' U L'" },
        { name: "", alg: "(U) L' R U R' U' R U R' U' L" },
        { name: "", alg: "(U) R U R' U L R U' R' U L'" },
        { name: "", alg: "(U') R U R' U' R2 D R' U R D' R' U R'" },
        { name: "", alg: "(U') F R U' R' U R U R2 F' R2 U R'" },
        { name: "", alg: "R U2 R' U2 R U2 R' U R U2 R'" },
        { name: "", alg: "(U') R U R' U2 R U' R2 D' R U R' D R" },
        { name: "", alg: "(U') R U2 R2 D' R U2 R' D R" },
        { name: "", alg: "(U2) L U' R U R' U' R U R' L'" },
        { name: "", alg: "(U) R U R' U' R U R'" },
        { name: "", alg: "(U) R U R' U' R U' R' U' R U' R'" },
        { name: "", alg: "(U) S R2 S' R2 U R' U' R U R2 U R'" },
        { name: "", alg: "R U2 R' U2 R U' R' U' R U' R'" },
        { name: "", alg: "(U) R U2 R D R' U' R D' R2 U' R U R'" },
        { name: "", alg: "(U) R U2 R' U2 R U' R' U R U R' U' R U2 R'" },
        { name: "", alg: "R2 D R' U R D' R' U R' U2 R U R'" },
        { name: "", alg: "(U) R U2 R' U R U' R2 D' R U R' D R" },
        { name: "", alg: "(U2) R U2 R' U2 R2 D R' U2 R D' R' U R'" },
      ],
    },
    {
      name: "",
      algs: [
        { name: "", alg: "R' U' S R2' S' R2 U R" },
        { name: "", alg: "(U') R U' R2 D' R U2 R' D R2 U R'" },
        { name: "", alg: "(U) R' F' R U R U' R' F" },
        { name: "", alg: "(U) R U' R' U R U2 R' U R U2 R' U R U' R'" },
        { name: "", alg: "(U2) R' U2 R F' R U R' U' R' F U2 R" },
        { name: "", alg: "R' D' R U' R' D R U R U R'" },
        { name: "", alg: "(U) R F R' U R U' F' R'" },
        { name: "", alg: "F' R U R' U' R' F R2 U R' U R U2 R'" },
        { name: "", alg: "(U') R U2 R' U R U' R' U' R U' R' U R U2 R'" },
        { name: "", alg: "R' D' R U2 R' D R U2 R U R'" },
        { name: "", alg: "(U2) D R' U' R U2 R' U' R D' R U R'" },
        { name: "", alg: "F' R U R' U' R' F R" },
        { name: "", alg: "R F U R' U' R F' U R' U R U2 R'" },
        { name: "", alg: "(U) S' R U' R' f R' F' R" },
        { name: "", alg: "(U) R U2 R' U R U2 R' U2 R U' R'" },
        { name: "", alg: "(U') R U2 R' F' R U2 R' U' R U' R' F" },
        { name: "", alg: "S' R U' R' f R' F' R" },
        { name: "", alg: "R U' R' U2 R U' R' U' R U R'" },
        { name: "", alg: "(U') R' U' R D' R U' R' D R' U2 R" },
        { name: "", alg: "(U') R U R' U2 R U2 R' U' R U2 R'" },
        { name: "", alg: "R' F R f' R U R' S" },
        { name: "", alg: "(U') R U2 R' U R U' R' U2 R U' R'" },
        { name: "", alg: "R U' R2' D' R U R' D R2 U R'" },
        { name: "", alg: "(U') R U R' U2 R U2 R' U2 R U' R'" },
        { name: "", alg: "(U') R U' R D R' U2 R D' R' U R'" },
        { name: "", alg: "(U) R U' R2' D' R U' R' D R2 U R'" },
        { name: "", alg: "R U' R' U' R U R' U R U R'" },
      ],
    },
    {
      name: "",
      algs: [
        { name: "", alg: "(U2) R' D' R U' R' D R U R U' R'" },
        { name: "", alg: "(U2) R U2 R' U R U R' U2 R U2 R'" },
        { name: "", alg: "(U2) R U' R' F' R U R' U R U2 R' F" },
        { name: "", alg: "R U' R' U R U R' U' R' D' R U R' D R" },
        { name: "", alg: "R U R2 D R' U2 R D' R' U2 R2" },
        { name: "", alg: "(U2) R U' R U2 R2 U' R2 U' R2" },
        { name: "", alg: "(U2) R U2 R' U R U R' U R U' R'" },
        { name: "", alg: "R U2 R' U2 F' R U R' U' R' F R" },
        { name: "", alg: "R U2 R' U' R' F' R U R U' R' F" },
        { name: "", alg: "(U2) R' D' R U' R' D R U2 R U2 R'" },
        { name: "", alg: "(U') R U2 R D R' U' R D' R' U R'" },
        { name: "", alg: "R U R' U' R U2 R' U R U R'" },
        { name: "", alg: "(U') R' F R U R U' R' F' U' R U' R'" },
        { name: "", alg: "(U) R U R' U R' D' R U' R' D R U R U' R'" },
        { name: "", alg: "(U2) R U2 R' U2 L' U R U' L U' R'" },
        { name: "", alg: "R U R' U R U R' U2 R U R'" },
        { name: "", alg: "(U2) R L' U' L U' L' U2 L U' R'" },
        { name: "", alg: "(U2) R U R' U2 R' D' R U R' D R2 U' R'" },
        { name: "", alg: "(U2) R U R' U2 R U' R' U2 R U2 R'" },
        { name: "", alg: "R U2 R' U R F U' R' U2 R U F' R'" },
        { name: "", alg: "R U R' U' R U2 R' U R U' R' U' R U' R'" },
        { name: "", alg: "(U2) R U R' U2 R U' R2 F R U R U' R' F'" },
        { name: "", alg: "R U' R' U' R U R' U2 R U' R' U R U' R'" },
        { name: "", alg: "(U2) R U R' U2 R U' R' L' U R U' R' L" },
        { name: "", alg: "R U' R2 F R U R U' R' F' U' R U' R'" },
        { name: "", alg: "(U2) R U R' U2 R U' R' U R U' R'" },
        { name: "", alg: "(U') R U2 R' U2 R U' R' U R U' R' U' R U R'" },
      ],
    },
    {
      name: "",
      algs: [
        { name: "", alg: "(U2) R U' R' D' R' D R U2 R' D' R D" },
        { name: "", alg: "(U') R U' R' U2 R U R2 D' R U' R' D R" },
        { name: "", alg: "(U') R U' R' U2 R2 U R' U R U2 R' U2 R'" },
        { name: "", alg: "(U2) R' D' R U2 R' D R2 U R'" },
        { name: "", alg: "(U2) R' U2 R2 U R' U' R' U2 R" },
        { name: "", alg: "(U) R U2 R' U R' U2 R2 U R2 U R" },
        { name: "", alg: "(U2) D R2 U2 R' U R U R2 D'" },
        { name: "", alg: "R U2 R' U2 R U R2 D' R U' R' D R" },
        { name: "", alg: "(U2) R U R' U F' R U R' U' R' F R" },
        { name: "", alg: "(U2) R' U2 R2 U R2 U R" },
        { name: "", alg: "(U2) R2 D R' U2 R D' R' U R'" },
        { name: "", alg: "(U') R U' R' U2 R U2 R' U2 R U R'" },
        { name: "", alg: "(U2) R U R' U R' D' R U2 R' D R U2 R U R'" },
        { name: "", alg: "(U2) R U' R' U2 R U R' U' R U' R' U R U' R'" },
        { name: "", alg: "(U2) R U' R' U R U' R' U2 R U' R'" },
        { name: "", alg: "(U) R U R' U R' U2 R2 U R2 U R" },
        { name: "", alg: "(U2) R U' R' U R U' R' U' R U2 R'" },
        { name: "", alg: "(U2) R U R' U2 R' F' R U R U' R' F" },
        { name: "", alg: "(U') R U R' U2 R2 D R' U2 R D' R' U R'" },
        { name: "", alg: "(U2) R' D' R U2 R' D R2 U2 R' U R U2 R'" },
        { name: "", alg: "(U') R U R' U2 R' U2 R2 U R2 U R" },
        { name: "", alg: "(U') R U' R' U' R U R' U' R U R'" },
        { name: "", alg: "R U2 R' U' R U R' U' R U R'" },
        { name: "", alg: "(U2) R U2 R' U2 R U2 R' U2 R U' R'" },
        { name: "", alg: "R' U' R U' R' U2 R2 U R'" },
        { name: "", alg: "(U2) R U D' R U' R' U' R U2 R' D R'" },
        { name: "", alg: "(U2) R U2 R' U2 R U2 R' U' R U2 R'" },
      ],
    },
    {
      name: "",
      algs: [
        { name: "", alg: "(U) L' U2 R U' R' U2 L" },
        { name: "", alg: "(U') R U' R'" },
        { name: "", alg: "(U2) R' F R U R U' R' F'" },
        { name: "", alg: "(U') R2 D R' U' R D' R2" },
        { name: "", alg: "(U') R U' R' U R' U' R U' R' U2 R" },
        { name: "", alg: "(U) R' D' R U2 R' D R2 U' R'" },
        { name: "", alg: "(U') R U R' U' R U' R'" },
        { name: "", alg: "(U') R' D' R U R' D R2 U2 R'" },
        { name: "", alg: "(U2) R' F' R U2 R U2 R' F" },
        { name: "", alg: "(U') R U2 R' U2 L R U' R' U L'" },
        { name: "", alg: "R' U' R U R U2 R' U2 R' U2 R" },
        { name: "", alg: "R U2 R'" },
        { name: "", alg: "(U') L' U2 R U' R' U' R U' R' L" },
        { name: "", alg: "R2 D R' U2 R D' R2" },
        { name: "", alg: "(U2) L' U R U' R' L" },
        { name: "", alg: "R U' R' U R U2 R'" },
        { name: "", alg: "F' R U2 R' U2 R' F R" },
        { name: "", alg: "(U') R U R2 U' R2 U' R2 U2 R" },
        { name: "", alg: "R' U' R2 U' R2 U2 R" },
        { name: "", alg: "(U') R U' R' U' R U R' U R U2 R'" },
        { name: "", alg: "(U') R U R D R' U2 R D' R2" },
        { name: "", alg: "R U' R' U R U' R' U R U2 R'" },
        { name: "", alg: "(U') R U' R' U R U2 R' U' R U' R'" },
        { name: "", alg: "R U' R D R' U' R D' R2" },
        { name: "", alg: "(U2) R2 U R' U R' U' R U R U2 R2" },
        { name: "", alg: "R U2 R' U R U R' U R U2 R'" },
        { name: "", alg: "(U') R U R' U' R U R' U' R U' R'" },
      ],
    },
    {
      name: "",
      algs: [
        { name: "", alg: "R U' R' U2 R U' R' U R U2 R' U R U2 R'" },
        { name: "", alg: "(U') R U' R' U2 R U' R' U R U2 R' U R U' R'" },
        { name: "", alg: "(U') R U2 R' U R U2 R' U R U' R'" },
        { name: "", alg: "(U) R U R' U2 R U' R' U R U R' U' R U R'" },
        { name: "", alg: "(U) R U' R' U R U2 R' U R U2 R'" },
        { name: "", alg: "S R2 S' R2 U R' U' R U R" },
        { name: "", alg: "(U) R2 D R' U R D' R2" },
        { name: "", alg: "(U) R U R' U2 R U R' U2 R U R'" },
        { name: "", alg: "(U') R U R' U R U' R' U R U R'" },
        { name: "", alg: "(U2) R U2 R' U R U' R' U2 R U' R' U2 R U' R'" },
        { name: "", alg: "(U) R U2 R' U2 R U' R' U R U2 R' U2 R U R'" },
        { name: "", alg: "(U2) R U2 R' U2 R U R' U2 R U' R'" },
        { name: "", alg: "(U') R U R' U R2 D R' U R D' R2" },
        { name: "", alg: "(U2) R U F R' U R U' F' R'" },
        { name: "", alg: "(U) R U' R2 U2 R U R' U R2 U' R'" },
        { name: "", alg: "(U) R U' R' U R U R'" },
        { name: "", alg: "(U) R2 U2 R2 U' R2 U' R2 U' R U R'" },
        { name: "", alg: "R' D' R U R' D R2 U' R' U R U R'" },
        { name: "", alg: "R2 U R' U R U2 R2" },
        { name: "", alg: "R U R' U R U2 R' U R U' R'" },
        { name: "", alg: "R U' R' U R2 U R' U R U2 R2" },
        { name: "", alg: "(U) R U' R' U R U' R' U' R U' R'" },
        { name: "", alg: "(U2) R U2 R' U2 R U R' U' R U2 R'" },
        { name: "", alg: "(U') R U' R' U' R U' R' U R U2 R' U R U' R'" },
        { name: "", alg: "(U) R U2 R' U' R U' R' U' R U R'" },
        { name: "", alg: "(U) R2 D R' U2 R D' R' U' R'" },
        { name: "", alg: "R' U' R U2 R U' R' U R U R2 U' R" },
      ],
    },
    {
      name: "",
      algs: [
        { name: "", alg: "(U2) R U' R' U R U2 R' U R U R'" },
        { name: "", alg: "(U2) R U' R2' D' R U2 R' D R" },
        { name: "", alg: "(U') R U' R' U' R U' R' U R U' R'" },
        { name: "", alg: "R U2 R' U' R U' R' U R U' R'" },
        { name: "", alg: "(U) R2 D R' U2 R D' R2' U' R U R'" },
        { name: "", alg: "R U R' U' R U' R' U2 R U' R'" },
        { name: "", alg: "(U2) R U R' U R U2 R' U2 R U R'" },
        { name: "", alg: "R U' R' U R' U2 R U R' U R2 U R'" },
        { name: "", alg: "R U R' U R2 U R' U R U2 R' U R'" },
        { name: "", alg: "(U2) R U2 R' U2 R U R' U R U R'" },
        { name: "", alg: "(U2) R U R' U2' R U R' U' R U R'" },
        { name: "", alg: "R U' R' U' R F R' U R U' F' U' R'" },
        { name: "", alg: "(U2) R U R' U R2 U R' U R U2 R' U2 R'" },
        { name: "", alg: "(U') R F R' U R U' F' U' R' U2 R U R'" },
        { name: "", alg: "R2 U2' R' U' R U' R2" },
        { name: "", alg: "(U) R' U' R U' R' U2 R U R U2 R'" },
        { name: "", alg: "(U') R2 U2' R' U' R U' R' U R'" },
        { name: "", alg: "(U) R U R D R' U2 R D' R2 U' R U R'" },
        { name: "", alg: "(U2) R F R' U R U' F' U' R'" },
        { name: "", alg: "(U2) R U2' R' U2 R U' R2' D' R U R' D R" },
        { name: "", alg: "(U2) R U2' R' U R U' R' U' R U R'" },
        { name: "", alg: "(U') R' U2' R U R' U R2 U R' U R U R'" },
        { name: "", alg: "(U2) R' U' R U' R' U2 R2 U2' R'" },
        { name: "", alg: "(U2) R' U' R U' R' U R2 U' R2' U2' R" },
        { name: "", alg: "(U') R U R2' U2' R U R' U R2 U R'" },
        { name: "", alg: "R U' R' U R2 U2 R' U' R U' R2" },
        { name: "", alg: "R' U2' R U R' U R2 U R'" },
      ],
    },
    {
      name: "",
      algs: [
        { name: "", alg: "(U2) R U2 R' U' R U2 R' U R U2 R'" },
        { name: "", alg: "R2 D R' U R D' R2 U2 R U' R'" },
        { name: "", alg: "(U2) R U' R' U' R U R' U R' D' R U R' D R" },
        { name: "", alg: "(U2) R U2 R' U R' D' R U' R' D R U' R U R'" },
        { name: "", alg: "(U') R2 D R' U2 R D' R2 U' R U2 R'" },
        { name: "", alg: "(U) R U2 R' U' R U R' U R U' R'" },
        { name: "", alg: "(U') R U' R' U2 R U' R' U' R U R' U2 R U' R'" },
        { name: "", alg: "(U2) R2 D R' U R D' R' U2 R' U' R U R'" },
        { name: "", alg: "(U') R U2 R' U' R U R' U2 R U' R'" },
        { name: "", alg: "(U2) R U' R D R' U' R D' R2 U' R U R'" },
        { name: "", alg: "(U) R U' R' U2 R U2 R' U R U' R'" },
        { name: "", alg: "(U2) R U' R' U2 R2 D R' U R D' R' U R'" },
        { name: "", alg: "(U2) R U R' U' R U R2 D' R U' R' D R" },
        { name: "", alg: "R2 D R' U R D' R2 U' R U2 R'" },
        { name: "", alg: "(U2) R U2 R' U' R U R'" },
        { name: "", alg: "(U) R' U2 R2 U R2 U R2 U R'" },
        { name: "", alg: "(U) R U2 R' U' R U R' U2 R U2 R'" },
        { name: "", alg: "(U2) R U R' U' R U2 R' U2 R U R'" },
        { name: "", alg: "(U2) R U2 R' U R' D' r U2 r' D R" },
        { name: "", alg: "(U') R U2 R' U R U' F R' U R U' F' R'" },
        { name: "", alg: "R U R' U' R U R' U2 R U' R'" },
        { name: "", alg: "(U) R U2 R' U R U' R' U2 R U R'" },
        { name: "", alg: "(U2) R U2 R' U' R U' R' U' R U' R'" },
        { name: "", alg: "(U) R U2 R' U' L U' R U R' L'" },
        { name: "", alg: "(U) R U' R' U2 R U2 R' U2 R U2 R'" },
        { name: "", alg: "(U') R U2 R' U' R U R' U' R U2 R'" },
        { name: "", alg: "R U R' U' R U R' U' R U2 R'" },
      ],
    },
    {
      name: "",
      algs: [
        { name: "", alg: "(U') R U' R' U2 R2 U R' U R U2 R' U R'" },
        { name: "", alg: "(U2) R U' R' U R U' R' U' R U R' U R U' R'" },
        { name: "", alg: "R U' R' U R U' R' U2 R U' R' U2 R U' R'" },
        { name: "", alg: "(U2) R2 U R' U R U2 R' U R' U2 R U R'" },
        { name: "", alg: "(U) R U R' F' R U R' U' R' F R U' R U' R'" },
        { name: "", alg: "(U2) R' D' R U2 R' D R U R U' R'" },
        { name: "", alg: "(U') R U R' U R U' R' U' R U2 R'" },
        { name: "", alg: "(U2) R U' R' U' R U2 R2 F R U R U' R' F'" },
        { name: "", alg: "(U2) R U R' U R' D' R U R' D R2 U' R'" },
        { name: "", alg: "(U') R U2 R2 D' R U2 R' D R2 U R'" },
        { name: "", alg: "(U) R U2 R' U' R U' R' U R U2 R'" },
        { name: "", alg: "(U2) R U' R' U' R U2 R' U R U' R'" },
        { name: "", alg: "(U2) R U' R' U' R U R' U2 R U' R' U2 R U R'" },
        { name: "", alg: "(U) R U2 R2 D' R U2 R' D R2 U' R'" },
        { name: "", alg: "(U) R U2 R2 D' R U' R' D R2 U2 R'" },
        { name: "", alg: "(U2) R U' R' U' R U2 R' U2 R U2 R'" },
        { name: "", alg: "(U2) R' D' R U2 R' D R U2 R U2 R'" },
        { name: "", alg: "(U') R U R' U R U' R' U2 R U' R'" },
        { name: "", alg: "(U) R U2 R' U' R U2 R'" },
        { name: "", alg: "(U2) R U R' U R U' R' U R U' R'" },
        { name: "", alg: "(U') R U' R' U F' R U R' U' R' F R" },
        { name: "", alg: "(U) R U2 R' U R' F R U R U' R' F'" },
        { name: "", alg: "R U' R' U2 R U R' U' R U2 R'" },
        { name: "", alg: "R U' R' U R U2 R' F' R U R' U' R' F R" },
        { name: "", alg: "(U2) R U' R' U2 R U' R' U R U' R' U R U R'" },
        { name: "", alg: "(U) R U2 R' U2 R U' R'" },
        { name: "", alg: "(U2) R U R' U R U' R' U2 R U2 R'" },
      ],
    },
    {
      name: "",
      algs: [
        { name: "", alg: "(U) R U2 R D R' U2 R D' R' U' R'" },
        { name: "", alg: "(U) R U R' U R U' R' U' R U' R'" },
        { name: "", alg: "(U2) R' U' R U' R' U2 R2 U R' U R U' R'" },
        { name: "", alg: "(U') R' U2 R2 U R2 U R U2 R U' R'" },
        { name: "", alg: "R' U' R U' R U R2 U R" },
        { name: "", alg: "R2 D R' U' R D' R2 U' R U R'" },
        { name: "", alg: "(U') R U R2 D' R U2 R' D R" },
        { name: "", alg: "(U') R U' R' U R U2 R' U2 R U R'" },
        { name: "", alg: "(U) R U2 R' U' R2 U R' U R U2 R2" },
        { name: "", alg: "(U') R U R' U R U2 R' U R U R'" },
        { name: "", alg: "(U2) R' D' R U R' D R2 U R'" },
        { name: "", alg: "(U) R U R' U R U' R D R' U2 R D' R2" },
        { name: "", alg: "R U2 R' U' R U2 R' U2 R U R'" },
        { name: "", alg: "(U) R U R' U R U R'" },
        { name: "", alg: "(U') R U' R' U2 R U R' U' R U R'" },
        { name: "", alg: "(U) R U R' U R U2 R' U R U2 R'" },
        { name: "", alg: "R U' R' U' R U R'" },
        { name: "", alg: "(U) R U' R2 D' R U R' D R" },
        { name: "", alg: "R U' R' U2 R U R D R' U R D' R2" },
        { name: "", alg: "(U') R' U2 R U R' U R U2 R U' R'" },
        { name: "", alg: "(U') R U R' U' R U R' U2 R U R'" },
        { name: "", alg: "(U2) R U' R' U R U R' U' R U2 R'" },
        { name: "", alg: "(U2) R2 D R' U R D' R' U R'" },
        { name: "", alg: "R U' R' U R U' R2 D' R U' R' D R" },
        { name: "", alg: "R' U' R U' R U R' U' R' U2 R" },
        { name: "", alg: "(U') R' U2 R U R' U R U' R U2 R'" },
        { name: "", alg: "(U2) R U2 R' U2 R U' R' U2 R U' R'" },
      ],
    },
    {
      name: "",
      algs: [
        { name: "", alg: "(U) R U2 R D R' U2 R D' R' U' R'" },
        { name: "", alg: "(U) R U R' U R U' R' U' R U' R'" },
        { name: "", alg: "(U2) R' U' R U' R' U2 R2 U R' U R U' R'" },
        { name: "", alg: "(U') R' U2 R2 U R2 U R U2 R U' R'" },
        { name: "", alg: "R' U' R U' R U R2 U R" },
        { name: "", alg: "R2 D R' U' R D' R2 U' R U R'" },
        { name: "", alg: "(U') R U R2 D' R U2 R' D R" },
        { name: "", alg: "(U') R U' R' U R U2 R' U2 R U R'" },
        { name: "", alg: "(U) R U2 R' U' R2 U R' U R U2 R2" },
        { name: "", alg: "(U') R U R' U R U2 R' U R U R'" },
        { name: "", alg: "(U2) R' D' R U R' D R2 U R'" },
        { name: "", alg: "(U) R U R' U R U' R D R' U2 R D' R2" },
        { name: "", alg: "R U2 R' U' R U2 R' U2 R U R'" },
        { name: "", alg: "(U) R U R' U R U R'" },
        { name: "", alg: "(U') R U' R' U2 R U R' U' R U R'" },
        { name: "", alg: "(U) R U R' U R U2 R' U R U2 R'" },
        { name: "", alg: "R U' R' U' R U R'" },
        { name: "", alg: "(U) R U' R2 D' R U R' D R" },
        { name: "", alg: "R U' R' U2 R U R D R' U R D' R2" },
        { name: "", alg: "(U') R' U2 R U R' U R U2 R U' R'" },
        { name: "", alg: "(U') R U R' U' R U R' U2 R U R'" },
        { name: "", alg: "(U2) R U' R' U R U R' U' R U2 R'" },
        { name: "", alg: "(U2) R2 D R' U R D' R' U R'" },
        { name: "", alg: "R U' R' U R U' R2 D' R U' R' D R" },
        { name: "", alg: "R' U' R U' R U R' U' R' U2 R" },
        { name: "", alg: "(U') R' U2 R U R' U R U' R U2 R'" },
        { name: "", alg: "(U2) R U2 R' U2 R U' R' U2 R U' R'" },
      ],
    },
    {
      name: "",
      algs: [
        { name: "", alg: "R' D' r U2 r' D R" },
        { name: "", alg: "(U2) R U R' U' R U R' U R U2 R'" },
        { name: "", alg: "(U2) R U' R' F' R U2 R' U2 R' F R" },
        { name: "", alg: "L R U' R' U L'" },
        { name: "", alg: "(U2) R U R'" },
        { name: "", alg: "(U2) R U R' U R' U2 R U R' U R" },
        { name: "", alg: "(U2) R U' R2 D' R U' R' D R2 U' R'" },
        { name: "", alg: "(U') L' R U R' U R U' R' U2 L" },
        { name: "", alg: "(U2) R U' R D R' U2 R D' R2'" },
        { name: "", alg: "(U2) R U2 R' U R U2 R'" },
        { name: "", alg: "(U2) R U' R' U R' D' R U2 R' D R2 U' R'" },
        { name: "", alg: "R U' R2 D' R U' R' D R" },
        { name: "", alg: "(U2) R U2 R' U R U' R' U R U' R' U R U2 R'" },
        { name: "", alg: "(U2) R U' R' U' R U R' U' R U' R'" },
        { name: "", alg: "R U R' U R U' R' U2 R U' R' U R U' R'" },
        { name: "", alg: "R' U2 R U R' U R U2 R U2 R'" },
        { name: "", alg: "(U2) R U' R' U' R U' R'" },
        { name: "", alg: "(U') R' D' R U2 R' D R U R U R'" },
        { name: "", alg: "(U2) R U2 R' U2 R' D' R U2 R' D R2 U' R'" },
        { name: "", alg: "R U R' U2 R U R' U2 R U2 R'" },
        { name: "", alg: "(U2) R U2 R' U R U' R' U R U2 R'" },
        { name: "", alg: "(U2) R U R2 U2 R U R' U R" },
        { name: "", alg: "(U2) R U2 R D R' U' R D' R2'" },
        { name: "", alg: "(U2) R U2 R' U R U2 R' U R U R' U R U2 R'" },
        { name: "", alg: "(U2) R U R' U R' U' R U' R' U2 R" },
        { name: "", alg: "(U) R U R D R' U R D' R2'" },
        { name: "", alg: "(U2) R U' R' U2 L' U R U' R' L" },
      ],
    },
    {
      name: "",
      algs: [
        { name: "", alg: "(U2) R U' R' U2 R U R'" },
        { name: "", alg: "(U') R U' R' U2 R' D' R U R' D R2 U' R'" },
        { name: "", alg: "R U R' U R2 D R' U' R D' R2" },
        { name: "", alg: "R U R' L' U2 R U2 R' U2 L" },
        { name: "", alg: "R U R' U R U R' U' R U' R'" },
        { name: "", alg: "(U2) R U' L U' R' U L'" },
        { name: "", alg: "L U' R U R' L'" },
        { name: "", alg: "(U2) R U' R' U2 R U2 R' U R U2 R'" },
        { name: "", alg: "R U R' U2 R U' R' U R U2 R'" },
        { name: "", alg: "(U) L U' R U R' L' U R U' R'" },
        { name: "", alg: "(U) F U R U' R' U R U' R2 F' R2 U' R'" },
        { name: "", alg: "R U R2 U2 R U R' U R2 U2 R'" },
        { name: "", alg: "(U') R U R' U R U2 R' U2 R U2 R' U R U' R'" },
        { name: "", alg: "R U R' U2 R U' R' U R U' R' U R U2 R'" },
        { name: "", alg: "(U2) R U2 R' U2 R U2 R' U R U R'" },
        { name: "", alg: "(U) R U2 R' U R U2 R' U' R U R'" },
        { name: "", alg: "R U R' U2 R2 D R' U2 R D' R2" },
        { name: "", alg: "(U) F U R U2 R' U2 R U R2 F' R2 U' R'" },
        { name: "", alg: "(U) R U2 R2 D' R U' R' D R" },
        { name: "", alg: "(U) R U R' U2 R U2 R' U R U' R'" },
        { name: "", alg: "R U R' U2 R U2 R'" },
        { name: "", alg: "(U') R U R' F' R U R' U R U2 R' F" },
        { name: "", alg: "(U2) R U R' U R U R' U' R U R'" },
        { name: "", alg: "R U R2 F' R U2 R U2 R' F" },
        { name: "", alg: "(U) R U R' U2 R U2 R' U2 R U2 R'" },
        { name: "", alg: "(U') R U' R' U2 R U' R' U R U' R'" },
        { name: "", alg: "(U') R' U' R U R U' R' U2 R' U2 R U R U' R'" },
      ],
    },
    {
      name: "",
      algs: [
        { name: "", alg: "R U R2 D' R U2 R' D R U R U' R'" },
        { name: "", alg: "(U') R U' R2 D' R U R' D R2 U' R'" },
        { name: "", alg: "R U R' U' R U2 R' U' R U2 R'" },
        { name: "", alg: "(U2) R' F R U R U' R' F' R U' R' U R U' R'" },
        { name: "", alg: "(U2) R U' R' U R2 D R' U R D' R2" },
        { name: "", alg: "(U2) R U2 R' U2 R2 D R' U R D' R2" },
        { name: "", alg: "(U) R2 D R' U' R D' R2 U2 R U R'" },
        { name: "", alg: "(U') R U2 R2 F' R U2 R U2 R' F" },
        { name: "", alg: "(U') R U2 R' U2 R U2 R'" },
        { name: "", alg: "(U') R' D' R U' R' D R2 U2 R' U2 R U R'" },
        { name: "", alg: "(U) R U' R' U' R U R' U2 R U2 R'" },
        { name: "", alg: "(U') R U' R2 D' R U R' D R U R U2 R'" },
        { name: "", alg: "(U') R U2 R' U2 R2 D R' U2 R D' R2" },
        { name: "", alg: "(U') R U2 R' U2 R U' R' U R U2 R'" },
        { name: "", alg: "(U') R U R' U2 R U' R' U2 R U R'" },
        { name: "", alg: "(U) R U' R' U R U' R' U2 R U R'" },
        { name: "", alg: "(U2) R U R' U2 R U' R' U R U2 R' U R U' R'" },
        { name: "", alg: "(U2) R U' R U R' U R U2 R2" },
        { name: "", alg: "(U') R U R' L U' R U R' L'" },
        { name: "", alg: "R U2 R' U R U' R' U R U' R'" },
        { name: "", alg: "(U') R U2 R' U R U' R'" },
        { name: "", alg: "(U) R U R' U R U2 R' U' R U R'" },
        { name: "", alg: "(U2) R U' R' U R U' R' U R U R'" },
        { name: "", alg: "(U2) R U2 R' U R2 U R' U R U2 R2" },
        { name: "", alg: "R U2 R' U R U' R' U2 R U2 R'" },
        { name: "", alg: "(U') R' U2 R U R' U' R U R' U R2 U' R'" },
        { name: "", alg: "R U R' U' R U2 R' U2 R U' R'" },
      ],
    },
  ],
};
